/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useSpring, animated } from "@react-spring/three";

export default function Shirt({ ...props }) {
  console.log(props.scroll);
  const group = useRef();
  const { nodes, materials } = useGLTF("/shirt.gltf");

  useFrame(() => {
    // Adjust the rotation factor if necessary
    const rotationFactor = 15;
    group.current.rotation.y = props.scroll * rotationFactor;
  });

  return (
    <group ref={group} {...props} dispose={null} scale={[8, 8, 8]}>
      <group position={[0, 0.1, 0]}>
        <animated.mesh
          geometry={nodes.Pattern_510522001.geometry}
          material={materials["t-shirt Knit_Cotton_Jersey_FRONT_217918"]}
        />
        <animated.mesh
          geometry={nodes.Pattern_510522001_1.geometry}
          material={materials["t-shirt Rib_2X2_468gsm mod_FRONT_217852"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/shirt.gltf");
